const firebase = require("firebase");

const firebaseConfig = {
  apiKey: "AIzaSyDfRqLw_maATHpGVqO4nxcmHw_asxc0c60",
  authDomain: "kval-c264a.firebaseapp.com",
  projectId: "kval-c264a",
  storageBucket: "kval-c264a.appspot.com",
  messagingSenderId: "692297808431",
  appId: "1:692297808431:web:d17649aabc7a6700f024da",
  measurementId: "G-EDTT5RXHJ2",
};

firebase.initializeApp(firebaseConfig);

const marques = [
  "Absorbine",
  "Adelar",
  "After Riding",
  "Akene",
  "Alliance Equine",
  "Alodis Care",
  "Albion",
  "Amerigo",
  "Animo Italia",
  "Antares",
  "Anna Scarpati",
  "Antares Sellier",
  "Apollo",
  "Axxel",
  "Back on Track",
  "Bamboo",
  "Bates",
  "Beaumont",
  "Belstar",
  "Beris",
  "Billybelt",
  "Borstiq farm",
  "Bockmann",
  "Butet",
  "Canter",
  "Casco",
  "Cavalleria Toscana",
  "Cavallo",
  "Carr & Day & Martin",
  "Charles Owen",
  "Cheval Liberté",
  "Chetak ",
  "Choplin",
  "Childeric",
  "Compositi",
  "CSO",
  "Cavaline",
  "Chetak",
  "Choplin",
  "Collection Equine",
  "Collorado Springs",
  "Continental",
  "CWD",
  "Dance With Him",
  "Delgrange",
  "Devoucoux",
  "Diego & Louna",
  "Dyon",
  "Ego7",
  "Equestrian Stockholm",
  "Equiline",
  "Equidura",
  "Equilibrium",
  "Equithème",
  "Equipe",
  "Eric Thomas",
  "Euroriding",
  "Eskadron",
  "Effax",
  "Effol",
  "Ekkia",
  "Equerry",
  "Equikids",
  "Equiconfort",
  "Equilibrium",
  "Equinatura",
  "Equiline",
  "Equizor",
  "EquiTrek",
  "Eric Thomas",
  "Eric le Tixerant",
  "Eskadron",
  "ES stockholm",
  "Excelsior",
  "Fautras",
  "Feeling ",
  "FFE",
  "Flags & Cup",
  "Fleck",
  "Flex On",
  "Freejump",
  "Feeling",
  "Fynalite",
  "France cheval",
  "Forestier",
  "Fouganza",
  "Freemax",
  "Gaston Mercier",
  "Galo’Snack",
  "GBS Sellier",
  "GEM",
  "GPA",
  "Guy Cantin",
  "Grooming Deluxe",
  "Haf",
  "Hagg",
  "HKM",
  "Happy mouth",
  "Happy Ross",
  "Harcour",
  "Hästko",
  "Heiniger",
  "Henri de Rivel",
  "Hervé Godignon",
  "Hexa",
  "HFI",
  "Hippotonic",
  "HDCP friandises pour chevaux",
  "Heiniger",
  "Hekktor Leather",
  "Helite",
  "Heritage",
  "Hermès",
  "Hey Sport",
  "Hit Air",
  "Horseware",
  "Horze",
  "HV polo",
  "Hydrophane",
  "Horse Pilot",
  "Horseware",
  "Ice Vibe",
  "Ifor Williams",
  "Inatake",
  "Jin Stittups",
  "Jean d’Autigny",
  "John Witaker",
  "Jumptec",
  "Jump Your Hair",
  "Jump’In",
  "Karitale",
  "Kazak Sport",
  "Kennedy Equi Products",
  "Kentucky Horsewear",
  "Kevin Bacon’s ",
  "Kep Italia",
  "Kieffer",
  "Kingsland",
  "Kris",
  "Laporatoire LPC",
  "Lamicell",
  "LAS",
  "LeMieux",
  "Leovet",
  "Lexington",
  "Le Sabotier",
  "Likit",
  "Lister",
  "Lorenzini",
  "Macel",
  "Marjoman",
  "Mattes",
  "Metalab",
  "Meyer",
  "Michel Vaillant",
  "Mondage",
  "Nacricare",
  "NAF",
  "Nathe",
  "Natural’ Innov",
  "Norton",
  "Officinalis",
  "Ogilvy Equestrian",
  "Onguent du Maréchal",
  "Optimum Time",
  "Orscana",
  "Oscar & Gabrielle",
  "Oxxer",
  "Paddock Sports",
  "Paskacheval",
  "Performance",
  "Pessoa",
  "Pikeur",
  "Pénélope Leprevost",
  "Phoenix",
  "Podium",
  "Prestige Italia",
  "Professional’s choice",
  "Protanner",
  "Pro Series",
  "Privilège Equitation",
  "Rapide",
  "Rambo",
  "Randol’s",
  "Ravene",
  "Rekor",
  "Riding world",
  "Reverdy",
  "Respire",
  "RG Italy",
  "Riding World",
  "Roeckl",
  "Ronzon",
  "SAPO",
  "Samshield",
  "Swing",
  "Seaver horse",
  "Segura",
  "Silver crown",
  "Stassek",
  "STX",
  "Sprenger",
  "Stubben",
  "Tattini",
  "TdeT",
  "Terrys",
  "treadstone",
  "TRC 85",
  "Tucci",
  "Uncle Jimmy’s",
  "Ungula Naturalis",
  "Uvex",
  "Veredus",
  "Vigot",
  "Waldhausen",
  "Weatherbeeta",
  "Whup&Go",
  "Westfalia",
  "Wintec",
  "Zandona",
  "Zaldi",
  "Autres marques",
];
marques.map(async (marque_name) => {
  await firebase.firestore().collection("Marques").add({
    name: marque_name,
  });
  console.log(marque_name, "added");
});
